CHANGELOG.md, bin/cssnext.js, test/cli.js, test/fixtures/config.css, test/fixtures/config.expected.css, test/fixtures/config.json
Feel free to change the flag name and the `input` & `output` options in the config file.
=> Add `config` option to CLI

CHANGELOG.md, README.md, index.js, package.json, test/fixtures/cases/example.css, test/fixtures/features/pseudo-elements.css, test/fixtures/features/pseudo-elements.expected.css
=> Added pseudoelements PostCSS Plugin

CHANGELOG.md, README.md, index.js, package.json, test/cli.js, test/option.compress.js
=> Added: compress option used cssnano instead of CSSWring

bin/cssnext.js
Misuse of chalk was not printing bug report URL as it should have been. `undefined` was printed instead.
=> Fixed undefined when printing bug report URL.

docs/content/index.md, docs/src/index.css, docs/src/modules/Header/index.css
- Position Header element on small device
- Position features on small device
- LIne height list of tools on small device
=> Fixed display element on small device

index.js, test/option.import.js
small fixes that avoid mutability error when passing options to atImport plugin
=> use object assign when passing options to atImport plugin

docs/src/index.css
On Firefox and Chrome (android) there is an overflow because of  `width:auto`, even if it's ok on iOS
before / after
=> Fixed width overflow on small device

package.json, src/index.js
cssnano 2 features built in 'quiet' removal of plugins, so disabling calc isn't necessary now.
=> Bump cssnano to v2.

src/__tests__/option.browsers.js, src/index.js
This PR will enable `pixrem` to use cssnext's own browsers option instead of requiring one of his own.
Addresses #263 and #174
=> Pass in browsers options to pixrem

docs/content/features.md
- Changes "Allow" to "Allows" at the start of the gray and nesting sections.
- Capitalises "A" in the `color()` function section.
☕
=> Quick typo fixes

docs/content/features.md, docs/content/index.md, docs/content/playground.html, package.json, src/__tests__/fixtures/features/replace-overflow-wrap.css, src/__tests__/fixtures/features/replace-overflow-wrap.expected.css, src/features.js
I've recently created a postcss-plugin to create a fallback from overflow-wrap to word-wrap and i think, it might be useful in the cssnext plugin pack:
Specification: https://drafts.csswg.org/css-text-3/#propdef-overflow-wrap
Plugin: https://www.npmjs.com/package/postcss-replace-overflow-wrap
Github-Repo: https://github.com/MattDiMu/postcss-replace-overflow-wrap
Browser Support (overflow-wrap vs word-wrap): http://caniuse.com/#feat=wordwrap
It's the first time, that I've ever contributed to cssnext, therefore I've simply worked through the Contributing.md guidelines and hopefully haven't forgotten anything.
Cheers
Matt
=> add overflow-wrap fallback

docs/content/features.md, docs/content/index.md, docs/content/playground.html, package.json, src/__tests__/fixtures/features/apply-rule.css, src/__tests__/fixtures/features/apply-rule.expected.css, src/features.js
Hi,
I'm not 100% sure about the plugin order, since it's supposed to be really similar with the custom properties one, I placed it next. 
So  basically all other transformations will happen on the applied rules, instead of the stored rules. Maybe in case of huge sets usage it could have an impact? 
I added [tests locally](https://github.com/pascalduez/postcss-apply/blob/master/test/integration.test.js) to the plugin to ensure it doesn't interfere with the custom properties one.
Refs #203
=> Add postcss-apply plugin

src/__tests__/fixtures/regression.css, src/__tests__/fixtures/regression.expected.css, src/__tests__/index.js
@MoOx I notice the comment about the order matters. I change the order and all the test pass. I tried to add some testing but I couldn't understand how it works. I need some help with that because I can't use @custom-selector inside the nested example.
fixes #297
=> fix nested selector with custom selectors

docs/src/index.css
=> Change features list style

docs/content/features.md, docs/content/index.md, docs/content/playground.html, package.json, src/__tests__/fixtures/features/attribute-case-insensitive.css, src/__tests__/fixtures/features/attribute-case-insensitive.expected.css, src/features.js
Specification: https://www.w3.org/TR/selectors4/#attribute-case
Plugin documentation: https://github.com/Semigradsky/postcss-attribute-case-insensitive
#111
=> Added new feature (attribute case insensitive)

CONTRIBUTING.md
Hi,
the `CONTRIBUTING` docs states for `src/__tests__/fixtures/cases/example.css` but this file no longer exist, removed in [eef525](https://github.com/MoOx/postcss-cssnext/commit/eef525a9fd086801224d029d572d3ca7982705c2). So I guess it's safe to prune?
=> Remove contributing docs about tests/cases

docs/content/features.md, docs/content/index.md, docs/content/playground.html, package.json, src/__tests__/fixtures/features/font-family-system-ui.css, src/__tests__/fixtures/features/font-family-system-ui.expected.css, src/features.js
[Specification](https://drafts.csswg.org/css-fonts-4/#valdef-font-family-system-ui) | [Plugin documentation](https://github.com/JLHwung/postcss-font-family-system-ui)
=> Add postcss-font-family-system-ui

docs/content/features.md, docs/content/index.md, docs/content/playground.html, package.json, src/__tests__/fixtures/features/image-set.css, src/__tests__/fixtures/features/image-set.expected.css, src/features-activation-map.js, src/features.js
=> Added: postcss-image-set-polyfill (#43)

package.json
postcss-cssnext added a polyfill for `css-image-set`. However, if the version one has installed of caniuse-db is too old (as often happens if you installed postcss-cssnext earlier and are upgrading - since peerDependencies are not upgraded if they still match the specified version range), the check for whether it is supported will fail.
=> Ensure a version of caniuse-db that includes css-image-set

docs/content/postcss.md
A few grammatical issues in `docs/content/postcss.md` made parts of the document hard to understand.
No content or opinions were changed. The only things changed were grammatical modifiers and sentence structure, hopefully allowing for more clarity to more users.
=> Fix grammatical issues in docs/content/postcss.md.

docs/content/postcss.md
postcss-cli maintainer here. In later versions, we've changed the config file format significantly. I've updated the usage examples to reflect this. I've also removed `postcss-reporter` from the example, since postcss-cli includes it by default anyhow.
=> Update postcss-cli usage example

package.json, src/__tests__/fixtures/features/font-family-system-ui.expected.css
The version 3.0 is ground-up rewritten and complies to https://github.com/postcss/postcss-plugin-boilerplate.
See https://github.com/JLHwung/postcss-font-family-system-ui/blob/3.0.0/CHANGELOG.md for the changelog.
=> chore(package): update postcss-font-family-system-ui to version 3.0

.travis.yml, appveyor.yml, package-lock.json
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.
https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
=> tests: use npm ci

.travis.yml, appveyor.yml
Node.js 4 is EOL and many dependencies do not support it anymore (see the failing appveyor tests on Windows).
=> chore: remove Node.js 4 (EOL), add Node.js 10
